#解决后续cmake文件路径问题
CMAKE_3PART_LIB_PATH=$1
CMAKE_3PART_INC_PATH=$2

mkdir -p ${CMAKE_3PART_LIB_PATH}/lib64/cmake

cp -rf ${CMAKE_3PART_LIB_PATH}/cmake/Drogon  ${CMAKE_3PART_LIB_PATH}/lib64/cmake
cp -rf ${CMAKE_3PART_LIB_PATH}/cmake/Trantor  ${CMAKE_3PART_LIB_PATH}/lib64/cmake

cp -rf ${CMAKE_3PART_LIB_PATH}/*drogon*  ${CMAKE_3PART_LIB_PATH}/lib64/
cp -rf ${CMAKE_3PART_LIB_PATH}/*trantor* ${CMAKE_3PART_LIB_PATH}/lib64/


DROGON_PATH=${CMAKE_3PART_INC_PATH}/drogon
sed -i "/INTERFACE_INCLUDE_DIRECTORIES*/c\INTERFACE_INCLUDE_DIRECTORIES \"${DROGON_PATH}/include/\"" ${CMAKE_3PART_LIB_PATH}/lib64/cmake/Drogon/DrogonTargets.cmake

TRANTOR_PATH=${CMAKE_3PART_INC_PATH}/trantor
sed -i "/INTERFACE_INCLUDE_DIRECTORIES*/c\INTERFACE_INCLUDE_DIRECTORIES \"${TRANTOR_PATH}/include/\"" ${CMAKE_3PART_LIB_PATH}/lib64/cmake/Trantor/TrantorTargets.cmake
