# 依赖StiBel库的内容 封装成StiBel.cmake文件
set(CMDTERM_BASE_PATH               "${CMAKE_CURRENT_SOURCE_DIR}")
set(CMDTERM_3PART_INCLUDE_PATH      "${CMDTERM_BASE_PATH}/include/3partlib")
set(CMDTERM_3PART_LIB_PATH          "${CMDTERM_BASE_PATH}/lib/3partlib")
set(CMDTERM_COMM_INCLUDE_PATH       "${CMDTERM_BASE_PATH}/include/comlib")
set(CMDTERM_COMM_LIB_PATH           "${CMDTERM_BASE_PATH}/lib/comlib")

set(DROGON_INCLUDE          ${CMDTERM_3PART_INCLUDE_PATH}/drogon/include)
set(TRANTOR_INCLUDE         ${CMDTERM_3PART_INCLUDE_PATH}/trantor/include)
set(JSONCPP_INCLUDE         ${CMDTERM_3PART_INCLUDE_PATH}/jsoncpp/include)
SET(GOOGLETEST_INCLUDE      ${CMDTERM_3PART_INCLUDE_PATH}/googletest/include)
SET(POCO_INCLUDE            ${CMDTERM_3PART_INCLUDE_PATH}/poco/include)

SET(STIBEL_COMMON_INCLUDE   ${CMDTERM_COMM_INCLUDE_PATH}/StiBel/Common/include)

set(CMAKE_INCLUDE_PATH  ${DROGON_INCLUDE} ${TRANTOR_INCLUDE} ${JSONCPP_INCLUDE} ${GOOGLETEST_INCLUDE} ${STIBEL_COMMON_INCLUDE} ${POCO_INCLUDE})
set(CMAKE_LIBRARY_PATH  ${CMDTERM_3PART_LIB_PATH})
LINK_DIRECTORIES(${CMDTERM_3PART_LIB_PATH} ${CMDTERM_COMM_LIB_PATH})

SET(LIB_GOOGLETEST  gtest)
SET(LIB_STIBEL_COMMON   StiBel_common_V2.1.1)
SET(LIB_POCO       
    PocoCrypto
    PocoJSON
    PocoRedis
    PocoEncodings
    PocoJWT
    PocoUtil
    PocoFoundation
    PocoNet
    PocoXML
)
SET(LIB_JSONCPP  jsoncpp)
# 依赖StiBel库的内容